### PR TITLE
abris #230 improve exception message and comments

### PR DESCRIPTION
**Pull request by cerveada**

### CODE REVIEW

**Comment by cerveada** [comment]
I removed SchemaManagerException. It causes the binary incompatibility errors, but it is not used anywhere, so I would delete it.

At the end I kept the condition as is, seems to me, it is not better reversed more like the same.

**Comment by kevinwallimann** [comment]
> I removed SchemaManagerException. It causes the binary incompatibility errors, but it is not used anywhere, so I would delete it.
> 
> At the end I kept the condition as is, seems to me, it is not better reversed more like the same.
I agree with that. The logic is not confusing, only the error message was. "Make sure that the Schema Registry is available, the parameters are correct" This part suggested that schema registry being unavailable could be the cause, which cannot be.

Unfortunately I think you can remove the SchemaManagerException due to binary compatibility reasons.

**Comment by cerveada** [comment]
> Unfortunately I think you cannot remove the SchemaManagerException due to binary compatibility reasons.

Are you afraid someone is catching it even though we never throw it?
If we want to be extra safe, we can keep it for that case.

**Comment by kevinwallimann** [comment]
> > Unfortunately I think you cannot remove the SchemaManagerException due to binary compatibility reasons.
> 
> Are you afraid someone is catching it even though we never throw it?
> If we want to be extra safe, we can keep it for that case.

No, I don't think anybody would do that. Then again, you never know. It's more a question of principles, whether we strictly adhere to binary compatibility and defer all incompatible changes to the next major version or we define a gray area where we accept incompatible changes. Probably we should first implement #159

**Review by kevinwallimann — APPROVED** [review]

**Review by jozefbakus — APPROVED** [review]

**Pull request merged**
