### PR TITLE
Handle malformed records by providing a PermissiveRecordExceptionHandler

### PR DESCRIPTION
**Pull request by willianmrs**
**Title**:
Handle malformed records by providing a PermissiveRecordExceptionHandler

**Problem**:
During the process of data ingestion, we noticed the application can fail if it encounters malformed Avro records. This type of failure was leading to interruptions in our data pipeline which can be problematic, particularly when dealing with large datasets.

**Solution**:
I've implemented a 'PermissiveRecordExceptionHandler' that substitutes any malformed records with fully null records, instead of letting the application crash. This approach allows the pipeline to continue processing the remaining data.

**Changes**:
Created a new PermissiveRecordExceptionHandler class.
The handle method in this class catches any exceptions during deserialization, logs a warning message, and replaces the malformed record with a fully null record.
Tests:
A new unit test PermissiveRecordExceptionHandlerSpec has been added. This test checks if the exception handler correctly replaces a problematic record with a fully null record when an exception occurs during deserialization.

The test first constructs an expected SpecificInternalRow with null values then triggers the exception handler by passing a new Exception and checks if the output matches the expected null record.

Test file: PermissiveRecordExceptionHandlerSpec.scala

Linked issue: https://github.com/AbsaOSS/ABRiS/issues/318

### CODE REVIEW

**Comment by willianmrs** [comment]
I've encountered an issue with the GitHub Actions workflow for this pull request. The error message "Error: HttpError: Resource not accessible by integration" indicates that the integration or GitHub App used for running the workflow does not have the necessary permissions to access the specified resource.

**Comment by cerveada** [comment]
@miroslavpojer Hi, do you know what could cause this issue? It is happening during test coverage phase.

**Comment by miroslavpojer** [comment]
> @miroslavpojer Hi, do you know what could cause this issue? It is happening during test coverage phase.

I' am doing analysis what is happening here. For now it looks to be this [Issue](https://github.com/actions/first-interaction/issues/10). **I am waiting for DevOps opinion for action github token configuration.**
I did code coverage manually to confirm state and get results missing here.

**Build Scala 2.12, Spark 3.2**
Reached 90% - OK.
image

**Build Scala 2.13, Spark 3.2**
Reached 90% - OK.
image

**Comment by Zejnilovic** [comment]
Hello @willianmrs, please update your branch with the newest master having, what I perceive to be, the fix for the GitHub action.

**Comment by cerveada** [comment]
I have merged the master myself, but it still fails.

**Comment by Zejnilovic** [comment]
image
Permissions are still not getting read correctly 🤷‍♂️

**Comment by willianmrs** [comment]
Hello guys, I saw that @cerveada already made the merging, but the error remains... Any idea?

**Comment by miroslavpojer** [comment]
Great work. Jacoco GitHub actions works now.

**Review by cerveada — APPROVED** [review]

**Review by kevinwallimann — APPROVED** [review]

**Pull request merged**
