### PR TITLE
Bump to confluent 5.5.1

### PR DESCRIPTION
**Pull request by dinedal**
Also had to patch `src/main/scala/za/co/absa/abris/avro/subject/SubjectNameStrategyAdapter.scala` to match changes with confluent schema registry.

### CODE REVIEW

**Comment by felipemmelo** [comment]
hi @dinedal , how are you?

Foremost, thank you very much for the contribution! Much appreciated.

It looks good enough, however, even though I have the dependencies for 5.5.1 synchronised, I haven't been able to import `io.confluent.kafka.schemaregistry.avro.AvroSchema`. I'll try to solve this and come back to you asap.

Thanks again,

Felipe.

**Comment by dinedal** [comment]
@felipemmelo I am good, happy to help and contribute.

We have been able to use this patch with confluent 5.5.1 successfully, and all the tests pass, so hopefully this change is sufficient.

**Review by cerveada — APPROVED** [review]
Seems OK to me, let's wait for Felipe.

**Review by felipemmelo — APPROVED** [review]
LGTM too

**Pull request merged**
