### PR TITLE
ABRiS #343 Add support for Apache Spark 4.0.0-SNAPSHOT with fewer exceptions

### LINKED ISSUE #343: Spark 3.4 Support
Is it planned to support spark 3.4.x ?

### PR DESCRIPTION
**Pull request by ni-mi**
Hi,

This pull request should close [issue 343](https://github.com/AbsaOSS/ABRiS/issues/343):
It seems like the snapshot of Spark 4.0.0 changed (again) the signature of AvroDeserializer's c'tor.
I added support for the new c'tor, while changing the code so it won't fail and recover - instead it just looks for a c'tor that is supported and use it.
If it can't find a c'tor - it throws NoSuchMethodException - but with a message that describes what c'tors are supported, so it will be easier to support more c'tors in the future.

### CODE REVIEW

**Comment by ni-mi** [comment]
@cerveada / @kevinwallimann I'd appreciate your review on this.

Thanks!

**Comment by SlevinBE** [comment]
I was experiencing the same issue as mentioned in https://github.com/AbsaOSS/ABRiS/issues/343#issuecomment-2012653699
I've tested this PR with Spark 3.5 on Databricks Runtime 14.3, which contains that new AvroDeserializer, and it solves that issue.
Also, great work on the code improvements and the better error reporting 👍

**Review by cerveada — APPROVED** [review]
LGTM, just read the code

**Comment by SlevinBE** [comment]
Since this also impacts those using Spark 3.5 when running on Databricks, it would be great to have a 6.4.1 release for this 🙏

**Comment by ni-mi** [comment]
Thanks @SlevinBE and @cerveada 🙏 
Can you merge?
AFAIK the CI check JaCoCo code-coverage failure seems to be unrelated - "HttpError: Resource not accessible by integration"

**Comment by cerveada** [comment]
>  AFAIK the CI check JaCoCo code-coverage failure seems to be unrelated - "HttpError: Resource not accessible by integration"

yeah, I am not worried about this.

Let's wait for @kevinwallimann

**Comment by ni-mi** [comment]
@kevinwallimann Can you please merge it - so we might be able to release a 6.4.1 release for Databricks?

Thanks!

**Comment by kevinwallimann** [comment]
> @kevinwallimann Can you please merge it - so we might be able to release a 6.4.1 release for Databricks?
> 
> Thanks!

Hi @ni-mi I've merged this PR and have just released a new version 6.4.1 to Maven Central. Thank you very much for your contribution!

**Pull request merged**
